sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - 7
  - 6
  - 5
  - 4
before_install:
  - npm install -g npm@latest
  - npm run compile
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run coveralls